### ISSUE TITLE
onConnectionStateChange failed: code=22 state=0 

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#10]
```
Non-fatal Exception: java.lang.Exception: onConnectionStateChange failed: code=22 state=0
       at solutions.s4y.itag.ble.ITagGatt$1.onConnectionStateChange(ITagGatt.java:163)
       at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:268)
       at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:789)
       at android.bluetooth.BluetoothGatt.-wrap0(Unknown Source)
       at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:264)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
       at android.os.Binder.execTransact(Binder.java:682)
```
```
Device
Brand: samsung
Model: SM-J600F
Orientation: Portrait
RAM free: 964.9 MB
Disk free: 7.4 GB
Operating System
Version: 8.0.0
Orientation: Portrait
Rooted: No
Crash
Date: Oct 19, 2018, 8:29:00 AM
App version: 1.0-beta7 (7)
```

**Comment by dsame** [comment]
Solved with code 133
