### ISSUE TITLE
False exception - should be warning/analytic

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#11]
Non-fatal Exception: java.lang.Exception: Not connected
       at solutions.s4y.itag.ble.ITagGatt.findITag(ITagGatt.java:432)
       at solutions.s4y.itag.ITagImageView.onLongPress(ITagImageView.java:87)
       at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:778)
       at android.view.GestureDetector.-wrap0(Unknown Source)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by dsame** [comment]
shown only in debug
