### ISSUE TITLE
nable to find explicit activity class {com.android.settings/com.android.settings.bluetooth.BluetoothSettings}

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#13]
Caused by android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.settings/com.android.settings.bluetooth.BluetoothSettings}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
       at android.app.Activity.startActivityForResult(Activity.java:3974)
       at android.app.Activity.startActivityForResult(Activity.java:3922)
       at android.app.Activity.startActivity(Activity.java:4257)
       at android.app.Activity.startActivity(Activity.java:4225)
       at solutions.s4y.itag.MainActivity.onOpenBTSettings(MainActivity.java:408)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.view.View$DeclaredOnClickListener.onClick(View.java:4504)
       at android.view.View.performClick(View.java:5272)
       at android.view.View$PerformClick.run(View.java:21555)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5701)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by dsame** [comment]
https://github.com/s4ysolutions/itag/commit/e42df8f517f9e13f780816edcb39d060f8b6dcc4
