### ISSUE TITLE
he content of the adapter has changed but ListView did not receive a notification

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#18]
Fatal Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131165246, class android.widget.ListView) with Adapter(class solutions.s4y.itag.LeScanFragment$Adapter)]
       at android.widget.ListView.layoutChildren(ListView.java:1799)
       at android.widget.AbsListView.onTouchUp(AbsListView.java:6560)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:6344)
       at android.widget.ListView.onTouchEvent(ListView.java:1700)
       at android.view.View.dispatchTouchEvent(View.java:12540)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3153)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
       at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6256)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3384)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:563)
       at android.view.View.dispatchPointerEvent(View.java:12788)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5675)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5470)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4963)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5016)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4982)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5119)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4990)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5176)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4963)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5016)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4982)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4990)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4963)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7742)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7682)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7643)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7853)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:197)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by dsame** [comment]
https://github.com/s4ysolutions/itag/commit/a89215f4abe0ac79fc2f2ad5457b7fb67f492a84
