### ISSUE TITLE
he content of the adapter has changed but ListView did not receive a notification

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#19]
Fatal Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131165246, class android.widget.ListView) with Adapter(class solutions.s4y.itag.LeScanFragment$Adapter)]
       at android.widget.ListView.layoutChildren(ListView.java:1700)
       at android.widget.AbsListView$CheckForTap.run(AbsListView.java:3475)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6798)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by dsame** [comment]
https://github.com/s4ysolutions/itag/commit/42139ea959fdd8883465ca60b0768b15f2febe04
