### ISSUE TITLE
Android 9 - Permission Denial: startForeground

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#24]
Caused by java.lang.SecurityException: Permission Denial: startForeground from pid=18645, uid=10171 requires android.permission.FOREGROUND_SERVICE
       at android.os.Parcel.createException(Parcel.java:1942)
       at android.os.Parcel.readException(Parcel.java:1910)
       at android.os.Parcel.readException(Parcel.java:1860)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
       at android.app.Service.startForeground(Service.java:695)
       at solutions.s4y.itag.ble.ITagsService.addToForeground(ITagsService.java:176)
       at solutions.s4y.itag.MainActivity.onPause(MainActivity.java:233)
       at android.app.Activity.performPause(Activity.java:7329)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4021)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3986)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3938)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by dsame** [comment]
https://github.com/s4ysolutions/itag/commit/7aba90f4173952a60f7635e4ca8b84f75eecb9bc
