### ISSUE TITLE
handle onServicesDiscovered failed: code=8

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#3]
```
Non-fatal Exception: java.lang.Exception: onServicesDiscovered failed: code=8
       at solutions.s4y.itag.ble.ITagGatt$1.onConnectionStateChange(ITagGatt.java:143)
       at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:268)
       at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:789)
       at android.bluetooth.BluetoothGatt.-wrap0(Unknown Source)
       at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:264)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
       at android.os.Binder.execTransact(Binder.java:682)
```

**Comment by dsame** [comment]
1. It is false message due to copy paste. It must be `GattCallback.onConnectionStateChange` 
2. It happens on disconnected iTag

Will be solved as part of the feature "React on disconnect"
