### ISSUE TITLE
handle onServicesDiscovered failed

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#33]
Non-fatal Exception: java.lang.Exception: onServicesDiscovered failed
       at solutions.s4y.itag.ble.ITagGatt$1.onServicesDiscovered(ITagGatt.java:271)
       at android.bluetooth.BluetoothGatt$1.onSearchComplete(BluetoothGatt.java:304)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:217)
       at android.os.Binder.execTransact(Binder.java:453)

**Comment by dsame** [comment]
workaround by 97a96de2fd51e04e6fcfaeef969a3a098156d543
