### ISSUE TITLE
Caused by android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#37]
Caused by android.content.res.Resources$NotFoundException: Resource "solutions.s4y.itag:drawable/app" (7f060046)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f060046 a=-1 r=0x7f060046}
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:3993)
       at android.content.res.Resources.loadDrawable(Resources.java:3905)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:776)
       at android.widget.ImageView.<init>(ImageView.java:151)
       at android.widget.ImageView.<init>(ImageView.java:140)
       at android.widget.ImageView.<init>(ImageView.java:136)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at solutions.s4y.itag.ITagsFragment.onCreateView(ITagsFragment.java:179)
       at android.app.Fragment.performCreateView(Fragment.java:2114)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
       at android.app.BackStackRecord.run(BackStackRecord.java:834)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1469)
       at android.app.Activity.performResume(Activity.java:6712)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4042)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4084)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3289)
       at android.app.ActivityThread.access$1000(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by dsame** [comment]
Brand: samsung
Model: Galaxy On7
Orientation: Portrait
RAM free: 419.95 MB
Disk free: 9.42 GB

**Comment by dsame** [comment]
can not reproduce

**Comment by dsame** [comment]
No solution

**Comment by dsame** [comment]
964162b4d7c71addd05205905657718a2a060e87
