### ISSUE TITLE
Fragment LeScanFragment{eb09346} not attached to Activity

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#38]
Fatal Exception: java.lang.IllegalStateException: Fragment LeScanFragment{eb09346} not attached to Activity
       at android.app.Fragment.getResources(Fragment.java:805)
       at android.app.Fragment.getString(Fragment.java:827)
       at solutions.s4y.itag.LeScanFragment$Adapter.getView(LeScanFragment.java:56)
       at android.widget.AbsListView.obtainView(AbsListView.java:2348)
       at android.widget.ListView.makeAndAddView(ListView.java:1876)
       at android.widget.ListView.fillUp(ListView.java:736)
       at android.widget.ListView.fillGap(ListView.java:675)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5082)
       at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4630)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:152)
       at android.app.ActivityThread.main(ActivityThread.java:5497)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dsame** [comment]
Device
Brand: OnePlus
Model: ONE A2005
Orientation: Portrait
RAM free: 499.4 MB
Disk free: 38.36 GB
Operating System
Version: 6.0.1
Orientation: Portrait
Rooted: No
Crash
Date: Nov 13, 2018, 9:13:00 PM
App version: 1.0-beta35 (35)

**Comment by dsame** [comment]
https://stackoverflow.com/questions/10919240/fragment-myfragment-not-attached-to-activity

**Comment by dsame** [comment]
https://stackoverflow.com/questions/28672883/java-lang-illegalstateexception-fragment-not-attached-to-activity/28673131

**Comment by dsame** [comment]
fixed in 64bf379ee9d71c9853ff0d7155e7e0638409e463
