### ISSUE TITLE
NullPointerException on ScanManager.registerScanner

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#40]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.bluetooth.gatt.ScanManager.registerScanner(java.util.UUID)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1969)
       at android.os.Parcel.readException(Parcel.java:1899)
       at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:878)
       at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:381)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:247)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:133)
       at android.bluetooth.BluetoothAdapter.startLeScan(BluetoothAdapter.java:2485)
       at android.bluetooth.BluetoothAdapter.startLeScan(BluetoothAdapter.java:2403)
       at solutions.s4y.itag.ble.LeScanner.startScan(LeScanner.java:171)
       at solutions.s4y.itag.MainActivity.onStartStopScan(MainActivity.java:363)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.view.View$DeclaredOnClickListener.onClick(View.java:5332)
       at android.view.View.performClick(View.java:6256)
       at android.view.View$PerformClick.run(View.java:24710)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:251)
       at android.app.ActivityThread.main(ActivityThread.java:6589)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by dsame** [comment]
can not reproduce

**Comment by dsame** [comment]
6b805369e7589d7c1f0bc637be239ff3c2ff36a8
