### ISSUE TITLE
Not allowed to start service Intent

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#57]
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=solutions.s4y.itag/.ble.ITagsService }: app is in background uid UidRecord{eaefb00 u0a154 SVC  idle change:uncached procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
       at android.app.ContextImpl.startService(ContextImpl.java:1550)
       at android.content.ContextWrapper.startService(ContextWrapper.java:664)
       at solutions.s4y.itag.ble.ITagsService.start(ITagsService.java:211)
       at solutions.s4y.itag.ble.ITagsService.start(ITagsService.java:219)
       at solutions.s4y.itag.MainActivity.onResume(MainActivity.java:233)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1514)
       at android.app.Activity.performResume(Activity.java:7305)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3911)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3951)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by dsame** [comment]
Operating System
Version: 9
Orientation: Portrait
Rooted: No
