### ISSUE TITLE
GATT error with 133 on onConnectionStateChange 

### ISSUE THREAD

**Issue by dsame** [s4ysolutions/itag#9]
https://github.com/googlesamples/android-BluetoothLeGatt/issues/44#issuecomment-349509171

```
Non-fatal Exception: java.lang.Exception: onConnectionStateChange failed: code=133 state=0
       at solutions.s4y.itag.ble.ITagGatt$1.onConnectionStateChange(ITagGatt.java:163)
       at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:181)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
       at android.os.Binder.execTransact(Binder.java:453)
```

```
Device
Brand: HUAWEI
Model: P8 Lite
Orientation: Portrait
RAM free: 594.23 MB
Disk free: 1.37 GB
Operating System
Version: 6.0
Orientation: Portrait
Rooted: No
Crash
Date: Oct 20, 2018, 7:22:00 PM
App version: 1.0-beta8 (8)
```

**Comment by dsame** [comment]
https://github.com/s4ysolutions/itag/commit/0bc21f059e3c11bd8f67623444abcdac3295386b
